# Generated by Django 5.1.4 on 2025-01-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='first_publish_year',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
